version: "3.4"

services:
    nginx:
        image: nginx:latest
        ports:
            - '8000:80'
        volumes:
            - ./code:/code
            - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: 
            dockerfile: ./Dockerfile.php
            context: .
        volumes:
            - ./code:/code
        depends_on: 
            - mysql
    mail:
        image: djfarrelly/maildev
        ports:
            - '1025:25'
            - '1080:80'        
    mysql:
        image: mysql:5.5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
            MYSQL_DATABASE: 'test'
        volumes:
            - ./mysql/database:/var/lib/mysql
            - ./mysql/initial:/docker-entrypoint-initdb.d
        ports:
            - '3333:3306'            